const fs=require('fs'),vm=require('vm');
const ctx={window:{},console,Date,Math};ctx.window.window=ctx.window;vm.createContext(ctx);
for(const f of ['calendar-core.js','temporal-core.js','universal-engine.js','calendar-registry.js','civilization-registry.js','advanced-systems.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});
const U=ctx.window.UniversalTemporalEngine,A=ctx.window.AdvancedTimeSystems,R=ctx.window.CalendarRegistry,T=ctx.window.TemporalCore;
function ok(cond,msg){if(!cond)throw new Error(msg);console.log('ok - '+msg)}
ok(U.STATUS.versioned?.label==='版本化','versioned capability status');
ok(U.STATUS.external?.label==='外部确认','external capability status');
ok(R.calendars.find(x=>x.id==='chinese')?.status==='full','modern Chinese lunisolar scoped Full');
ok(R.calendars.find(x=>x.id==='tibetan')?.status==='versioned','Tibetan calendar is a versioned multi-engine family');
ok(U.getPlugin('chinese-almanac')?.status==='versioned','Chinese almanac versioned RuleSet');
ok(U.getPlugin('indian-panchanga')?.status==='experimental','Panchanga prototype explicitly experimental');
ok(U.getPlugin('maya-ritual')?.status==='full','Maya ritual cycles Full under declared correlation');
const maya=A.mayaRitual(584283);
ok(maya.tzolkin.text==='4 Ajaw','Maya GMT epoch Tzolkin 4 Ajaw');
ok(maya.haab.text==='8 Kumkʼu','Maya GMT epoch Haab 8 Kumkʼu');
const hj=A.huangjiForYear(-2336);
ok(hj.shi===2157 && hj.yearInShi===1,'Huangji anchor 2337 BCE = shi 2157 year 1');
ok(hj.hexagram&&hj.ruleSetId==='hjys-fuxi-circle-60-hierarchy-lichun-v1','Huangji annual hexagram uses a versioned hierarchical RuleSet');
ok(A.huangjiForYear(1984).hexagram.shortName==='鼎','Huangji 1984 Jiazi starts at Ding under Da Guo -> Gou -> Ding');
ok(A.huangjiForYear(2025).hexagram.shortName==='革'&&A.huangjiForYear(2026).hexagram.shortName==='同人','Huangji verified modern annual sequence is 2025 Ge -> 2026 Tong Ren');
ok(A.huangjiForYear(2044).coordinate.annualSequenceStartHexagram.shortName==='大过','Huangji recomputes the 2044 Jiazi start from its upper hierarchy');
const lc2026=T.liChunInstant(2026),loc={timezone:'Asia/Shanghai',utcOffsetMinutes:480};
ok(A.huangjiForDate(new Date(+lc2026-1000),loc).huangjiYear===2025&&A.huangjiForDate(new Date(+lc2026+1000),loc).huangjiYear===2026,'Huangji switches annual hexagram at the Li Chun instant');
for(const y of [-10000,-2336,1,2026,12000])ok(!['乾','坤','坎','离'].includes(A.huangjiForYear(y).hexagram.shortName),`Huangji excludes four cardinal hexagrams for year ${y}`);
const p=A.panchangaApprox(new Date('2026-08-10T12:00:00Z'));
ok(p.tithi.index>=1&&p.tithi.index<=30&&p.nakshatra.index>=1&&p.nakshatra.index<=27,'Panchanga prototype ranges');
const w=A.pawukonStructural(2461263);
ok(w.cycleDay>=1&&w.cycleDay<=210&&w.cycles.dasa>=1&&w.cycles.dasa<=10,'Pawukon structural cycles');
const html=fs.readFileSync('index.html','utf8');
ok(html.includes('globalPlaceSearch')&&html.includes('earthLeafletMap'),'search + real map location UI');
const appjs=fs.readFileSync('app.js','utf8');
ok(appjs.includes("CN:'Asia/Shanghai'")&&appjs.includes('administrativeTimeFallback'),'administrative timezone fallback keeps mainland China on UTC+8 when timezonefinder is absent');
const server=fs.readFileSync('server.py','utf8');
ok(server.includes('/api/tibetan/day')&&server.includes('TIBETAN_OK'),'optional Tibetan API is wired');
ok(/v1\.[2-9]\.[0-9]+/.test(html),'v1.2+ resources preserve v1.1 feature set');
console.log('V1.1.0 regression feature tests passed under v1.2+');
